# Generated by Django 4.1.5 on 2023-09-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_products_price'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='product',
            field=models.ForeignKey(default='23', on_delete=django.db.models.deletion.CASCADE, to='application.products'),
        ),
    ]
