# Generated by Django 4.1.5 on 2023-09-29 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0008_products_price'),
        ('chat', '0002_chat_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(default='5', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default='23', on_delete=django.db.models.deletion.CASCADE, to='application.products')),
            ],
        ),
    ]
